import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { sectionOneLayout, sectionTwoLayout } from '../components/elements';
import Layout from '../components/Layout';
import Navigation from '../components/Navigation';
import { getUserById, getValidSessionByToken } from '../util/database';

// type Props = {
//   user: User;
// };

export default function Home(props) {
  return (
    <Layout userObject={props.userObject}>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Landing page" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h1>Welcome X</h1>
      <p>It's great to have you with us.</p> */}
      <section css={sectionOneLayout}>
        <Navigation userId={props.user.id} />
      </section>
      <section css={sectionTwoLayout}>
        <h1>
          Hello {props.user.username} User_id: {props.user.id}{' '}
        </h1>
        <div>
          <article>
            <h2>Text 1</h2>
            <p>Lorem Ipsum Lorem Ipsum Lorem Ipsum </p>
            <button>Documents</button>
          </article>
          <article>
            <div>
              <h2>Text 1</h2>
              <p>Lorem Ipsum Lorem Ipsum Lorem Ipsum </p>
              <Link href="/documents" passHref>
                <button>Documents</button>
              </Link>
            </div>
            <div>
              <h2>Text 2</h2>
              <p>Lorem Ipsum Lorem Ipsum Lorem Ipsum </p>
              <button>Updates</button>
            </div>
            <div>
              <h2>Text 3</h2>
              <p>Lorem Ipsum Lorem Ipsum Lorem Ipsum </p>
              <button>Profile</button>
            </div>
            <div>
              <h2>Text 3</h2>
              <p>Lorem Ipsum Lorem Ipsum Lorem Ipsum </p>
              <button>Profile</button>
            </div>
          </article>
        </div>
      </section>
    </Layout>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  // 1. Check if there is a token
  const token = context.req.cookies.sessionToken;

  if (token) {
    // 2. check if token is valid
    // TO DO CHECK ROLE Of USER

    const session = await getValidSessionByToken(token);
    const user = await getUserById(session.userId);

    if (session) {
      return {
        props: {
          user: user,
        },
      };
    }
  }

  // 3. if token is NOT valid redirect to login
  return {
    redirect: {
      destination: '/login',
      permanent: false,
    },
  };
}

/* import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello</h1>
      </main>

      <footer>
        <p>This is a footer</p>
      </footer>
    </div>
  );
}
 */
